### ISSUE TITLE
Request for training Log

### ISSUE THREAD

**Issue by ArchiMickey** [khokao/diffusion-autoencoders#7]
Hi. Thank you for your brilliant work. This repo is much cleaner than the official implementation. I am currently an undergraduate student so I have a single 4090 only. I want to train a diffae for my own research. Can you provide any training log that includes the training loss? It will be handy for me to know whether my training will work.

**Comment by khokao** [comment]
Hi, @ArchiMickey . Thank you for your kind words. I'm glad to hear that you appreciate my work!
Unfortunately, I don't have any training logs available. I apologize for not being able to be of more assistance.
